"""new user fields

Revision ID: 759244e9899b
Revises: 54ad49fa6d2c
Create Date: 2021-11-05 21:52:24.183754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759244e9899b'
down_revision = '54ad49fa6d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
